Backend/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path("login/", views.loginPage, name="login"),
    path("logout/", views.logoutUser, name="logout"),
    path("register/", views.registerPage, name='register')
]

Backend/chunkfile/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('modders/', admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include('accounts.urls')),
    path("split/", include("split_file.urls")),
]

Backend/main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.AboutUs, name="about"),
    path("faq/", views.FaQ, name="faq"),
    path("contact/", views.contact, name="contact"),
    path('policy/', views.policy, name='policy'),
    path('policy/', views.policy, name='policy'),
    path('terms/', views.terms, name='terms'),
    ]
#if settings.DEBUG:
    #creates a last urlpattern - with the media url, so, whatever path is in the media_url is made a url pattern
    #
        #urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/split_file/urls.py
from django.urls import path
from . import views

app_name = 'split_file'
urlpatterns = [
    path("", views.split_home, name='split_home'),
    path("csv/", views.split_csv, name='split_csv'),
    path("json/", views.split_json, name='split_json'),
]

Backend/split_file/models.py
from time import timezone
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

class ChunkCsv(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    

Backend/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
        

Backend/main/forms.py
from django import forms
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
        

Backend/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm 
from .forms import CreateUserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


    #login user view
def loginPage(request):
    if request.user.is_authenticated:
        return redirect('main:index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            
            if user is not None:
                login(request, user)
                return redirect('split_file:split_home')
            else:
                messages.info(request, "Password or email is incorrect")
                
        return render(request, 'accounts/signin.html')
    
    #log-out view
def logoutUser(request):
    logout(request)
    return redirect('accounts:login')

    #register-user view
def registerPage(request):
    if request.user.is_authenticated:
        return redirect('main:index')
    else:
        form = CreateUserForm()
        
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('split_file:split_home')
            else:
                messages.error(request, "Error in registering user:")
                
        context = {'form':form}
        return render(request, 'accounts/signup.html', context)

Backend/main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, "main/index.html")

def AboutUs(request):
    return render(request, "main/about.html")

def FaQ(request):
    return render(request, "main/faq.html")

def contact(request):
    return render(request, "main/contact_us.html")

def policy(request):
    return render(request, "main/privacypolicy.html")

def terms(request):
    return render(request, "main/termsandconditions.html")

Backend/split_file/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required(login_url="accounts:login")
def split_home(request):
    return render(request, 'split_file/home.html')

@login_required(login_url="accounts:login")
def split_csv(request):
    if request.method == 'POST':
        uploaded_file = request.FILES['csv_file']
        #print uploaded_file size and name
    return render(request, 'split_file/splitcsv.html')

@login_required(login_url="accounts:login")
def split_json(request):
    return render(request, 'split_file/split_json.html')

Backend/templates/accounts/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/signin.css' %}">
  <title>Sign In</title>
</head>

<body>

  <div class="mobile-logo">
    <img src="{% static 'images/default-1.png' %}" alt="logo">
  </div>

  <div class="body">
    <section>
      <div class="img-and-logo">

        <div class="logo">
          <img src="{% static 'images/chunkfile hi logo.png' %}" alt="logo">
        </div>

        <div class="image-section">
          <img src="{% static 'images/pana.png' %}" alt="img" class="img">
        </div>

      </div>
    </section>

    <div class="form-section">

      <div class="sign-in-header">
        <h1>Sign In</h1>
      </div>

      <header>
        <p class="header-text">Hello Again!</p>
        <p class="header-sub-text">Welcome back, you've been missed!</p>
      </header>

      <p>{% for message in messages %} {{ message }} {% endfor %}</p>

      <form action="#" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <label for="username">Username</label>
        <input type="text" name="username" id="username" required placeholder="Enter Username">

        <label for="password">Password</label>
        <input type="password" name="password" id="password" required placeholder="Enter Password">

        <a href="#" class="forgotten-password"> Forgot Password? </a>

        <button type="submit" class="btn-2" value="submit" type="submit" style="cursor: pointer">
          Log In
        </button>

      </form>

      <div class="form-bottom-text">
        <p class="line"></p>
        <p class="cont">Or continue with</p>
        <p class="line"></p>
      </div>

      <div class="button-section">
        
        <button class="sign-up-btn1 fb">
          <a href="#" class="sign-up-btn">
            <img src="{% static 'images/Facebook logo.png' %}" alt="fb" class="icon" />
            Facebook
          </a>
        </button>

        <button class="sign-up-btn1 ggle">
          <a href="#" class="sign-up-btn">
            <img src="{% static 'images/Google logo.png' %}" alt="google" class="icon" />
            Google
          </a>
        </button>

      </div>

      <div class="footer">
        <p>Don't have an account yet?</p>
        <a href="{% url 'accounts:register' %}" class="reg">Register</a>
      </div>
      
    </div>
  </div>

</body>

</html>

Backend/templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <title>Sign Up</title>
    <style>
        .errorlist {
            list-style-type: square;
            font-size: 1em;
            color: red;
        }
    </style>
</head>


<body>

    <section class="side-1">
        <div class="img-and-logo">
            
            <div>
                <img src="{% static 'images/chunkfile hi logo.png' %}" alt="logo" class="logo">
            </div>

            <div class="image-section">
                <img src="{% static 'images/amico.png' %}" alt="img" class="img">
            </div>

        </div>
    </section>

    <div class="mobile-logo">
        <img src="{% static 'images/default 1.png' %}" alt="logo" class="logo">
    </div>

    <section class="form-and-image-section">
        <div class="form-section">

            <div class="form-section-sub">
                <h1>Create An Account</h1>
                <p class="form-text"> One account for everything split, and more</p>
            </div>

            <div class="button-section">

                <button class="sign-up-btn1">
                    <a href="#" class="sign-up-btn">
                        <img src="{% static 'images/Google logo.png' %}" alt="google" class="icon">
                        Sign up with google
                    </a>
                </button>

                <button class="sign-up-btn1">
                    <a href="#" class="sign-up-btn">
                        <img src="{% static 'images/Facebook logo.png' %}" alt="fb" class="icon">
                        Sign up with Facebook
                    </a>
                </button>

            </div>

            <div class="form-bottom-text">
                <p class="line"></p>
                <p class="cont"> OR </p>
                <p class="line"></p>
            </div>

            <form action="#" method="POST" class="form" enctype="application/x-www-form-urlencoded">
                {% csrf_token %}
                
                <label for="username">Username</label>
                {{form.username}}
                
                <label for="email">Email Address</label>
                {{form.email}}

                <label for="password">Password</label>
                {{form.password1}}

                <label for="password">Confirm password</label>
                {{form.password2}}

                <p class="ack-text">
                    By creating account, you agree to our <span> <a href="#" class="tnc-links">Terms</a></span> and have read and<br>
                    acknowledge our <span> <a href="{% url 'main:policy' %}" class="tnc-links">Privacy Statement</a> </span>
                </p>

                <p>
                    {% for message in messages %}
                        {{message}}
                    {% endfor %}

                    {{form.errors}}
                </p>

                <button type="submit" class="btn-3" style="cursor: pointer;">
                    Create account
                </button>

                <div class="foot-text">
                    <p>
                        Already have an account? <span> <a href="{% url 'accounts:login' %}"> Login </a> </span>
                    </p>
                </div>

                <div class="mobile-btn-sec">
                    <button class="sign-up-btn1 ggle">
                        <a href="#" class="sign-up-btn">
                            <img src="../signin assets/Google logo.png" alt="google" class="icon">
                            <p class="icon-text">Google</p>
                        </a>
                    </button>
    
                    <button class="sign-up-btn1 fb">
                        <a href="#" class="sign-up-btn">
                            <img src="../signin assets/Facebook logo.png" alt="fb" class="icon">
                            <p class="icon-text">Facebook</p>
                        </a>
                    </button>
                    
                </div>
            </form>
        </div>
    </section>

    <script>
        var placeholders = document.getElementsByTagName('input');
        placeholders[1].placeholder = 'creative-lunar999';
        placeholders[2].placeholder = 'john@doe.com';

    </script>
</body>
</html>

Backend/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    {% block title %}
    {% endblock title %}
    {% block meta %}
    {% endblock meta %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans&family=Fraunces:opsz,wght@9..144,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
  </head>
  <body>

    {% block content %}  {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
    <script>
      window.cookieconsent.initialise({
        "palette": {
          "popup": {
            "background": "#000"
          },
          "button": {
            "background": "#f1d600"
          }
        },
        "theme": "edgeless",
        "position": "top",
        "static": true,
        "content": {
          "message": "This website uses cookies to ensure you get the best experience on our website", 
          "dismiss": "Got it!",
          "link": "Learn more"
        }
      });
      </script>

  </body>
</html>

Backend/templates/footer.html
{% load static %}


 <!-- THE FOOTER -->
 <footer class="footer-container">
    <div class="footer-top">
        <!-- column 1 -->
        <div class="column first">
            <img class="footer-logo" src="{% static 'images/footer-logo.svg' %}" alt="Logo" />

            <p class="tagline">Split your CSV and JSON files the easy way...</p>
            <div class="social">

                <a href="#">
                    <i class="fa fa-facebook" style="color: rgb(14, 36, 235); font-size:30px;"></i>
                </a>

                <a href="#">
                    <i class="fa fa-twitter" style="color: rgb(0, 140, 255); font-size:30px;"></i>
                </a>

                <a href="#">
                    <i class="fa fa-github" style="color: rgb(23, 26, 29); font-size:30px;"></i>
                </a>

            </div>
        </div>

        <!-- column 2  -->
        <div class="column second">
            <h2 class="column-heading">Product</h2>
            <p>App Integration</p>
            <p>Tools</p>
        </div>

        <!-- column 3  -->
        <div class="column third">
            <h2 class="column-heading">Company</h2>
            <p><a style="text-decoration: none;color:white;" href="{% url 'split_file:split_home' %}" >Home</a></p>
            <p><a style="text-decoration: none;color:white;" href="{% url 'main:about' %}" >About</a></p>
            <p><a style="text-decoration: none;color:white;" href="{% url 'main:terms' %}" >Terms and Conditions</a></p>
            <p><a style="text-decoration: none;color:white;"  href="{% url 'main:policy' %}" >Privacy Policy</a></p>
            <p><a style="text-decoration: none;color:white;" href="{% url 'main:contact' %}" >Contact Us</a></p>
            <p><a style="text-decoration: none;color:white;" href="{% url 'main:faq' %}" >FAQ</a></p>
        </div>

        <!-- column 4  -->
        <div class="column fourth">
            <h2 class="column-heading">Tools</h2>
            <p><a style="text-decoration: none;color:white;" href="{% url 'split_file:split_csv' %}" >Split CSV</a></p>
            <p>Split JSON</p>
            <p>Convert CSV</p>
            <p>Convert JSON</p>
            <p>Merge CSV</p>
            <p>Merge JSON</p>
        </div>
    </div>
    <div class="footer-bottom">
        <div>&copy; 2022 ChunkFile. All rights reserved.</div>

        <p><span>12,000</span> Files splitted</p>
    </div>
</footer>

Backend/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Chunk File</title>
	<meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

	<!--Cookie consent-->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
	<script src="{% static 'js/cookie.js' %}"></script>
	<script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>
</head>
		

	<body>
		<header>
			{% if request.user.is_authenticated %}
			<nav class="nav">
				<!-- logo -->
				<div class="logo-container">
					<h1 class="logo-text">ChunkFile</h1>
				</div>
				<div class="nav-btn">
					<span class="btn sign-up">Hi, {{request.user}}</span>
					<a href="" class="btn sign-up" style="text-decoration: none;"><span>Account <i class="fa fa-user"></i></span></a>
				</div>

				<div class="bars">
					<img src="{% static 'images/menu.svg' %}" alt="Menu">
				</div>
			</nav>
			{% else %}
				<nav class="nav">
					<!-- logo -->
					<div class="logo-container">
						<h1 class="logo-text">ChunkFile</h1>
					</div>
					<div class="nav-btn">
						<a href="{% url 'accounts:login' %}" class="btn sign-in" style="text-decoration: none;">Sign in</a>
						<a href="{% url 'accounts:register' %}" class="btn sign-up" style="text-decoration: none;">Sign up</a>
					</div>

					<div class="bars">
						<img src="{% static 'images/menu.svg' %}" alt="Menu">
					</div>
				</nav>
			{% endif %}
		</header>

		<main>
			<!-- hero section  -->
			<section>
				<div class="container hero-container">
					<!-- hero cta  -->
					<div class="hero-left">
						<h1 class="hero-title">
							The Easy Way to Break Your Files into Smaller Bits
						</h1>
						<p class="hero-desc">
							We give you 100% free access to split your CSV and JSON files into
							bits merge and convert the easy way
						</p>
						<a href="{% url 'split_file:split_home' %}" class="hero-btn" style="text-decoration: none;">Get started</a>
					</div>

					<!-- hero image -->
					<div class="hero-right">
						<img src="{% static 'images/hero.svg' %}" alt="" />
					</div>
				</div>
			</section>

			<!-- top features  -->
			<section class="  ">
				<div class="container features-container">
					<h1 class="section-title">Our Top Features</h1>
					<div class="features">
						<!-- Splitter  -->
						<div class="feature-box">
							<h3 class="feature-title">Splitter</h3>
							<p class="feature-desc">Split your CSV and JSON file</p>
						</div>

						<!-- Converter  -->
						<div class="feature-box">
							<h3 class="feature-title">Converter</h3>
							<p class="feature-desc">Convert your CSV and JSON file</p>
						</div>

						<!-- Merger  -->
						<div class="feature-box">
							<h3 class="feature-title">Merger</h3>
							<p class="feature-desc">Merge your CSV and JSON file</p>
						</div>
					</div>
				</div>
			</section>

			<!-- why us -->
			<section>
				<div class="container why-container">
					<h1 class="section-title">Why Choose us?</h1>
					<div class="why">
						<!-- user friendly  -->
						<div class="why-reason">
							<div class="why-head">
								<img class="" src="" alt="" />
								<h3 class="why-title">User Friendly</h3>
							</div>
							<p class="why-desc">
								Our Tools are simple to navigate, with just a few clicks you can
								split, merge, and convert your CSV and JSON files easily. Your
								files are easily accessible with the option to save and download
								later at anytime.
							</p>
						</div>

						<!-- secure -->
						<div class="why-reason">
							<div class="why-head">
								<img class="" src="" alt="" />
								<h3 class="why-title">Secure</h3>
							</div>
							<p class="why-desc">
								To protect our users information, We use the latest 256-bit TLS
								encryption algorithm and secure infrastructure which guarantees
								the security of users data
							</p>
						</div>

						<!-- 100% Free  -->
						<div class="why-reason">
							<div class="why-head">
								<img class="" src="" alt="" />
								<h3 class="why-title">100% Free</h3>
							</div>
							<p class="why-desc">
								Our platform provides 100% free and reliable access to online
								splitting, merging, and converting tools to help you solve your
								files problem.
							</p>
						</div>

						<!-- API Integration -->
						<div class="why-reason">
							<div class="why-head">
								<img class="" src="" alt="" />
								<h3 class="why-title">API Integration</h3>
							</div>
							<p class="why-desc">
								With ChunkFile’s simple API integration system, files can easily
								be transformed to produce smaller bits, different formats, and
								combined data with an option to save or download.
							</p>
						</div>

						<!-- Online Sync -->
						<div class="why-reason">
							<div class="why-head">
								<img src="" alt="" />
								<h3 class="why-title">Online Sync</h3>
							</div>
							<p class="why-desc">
								You can split your files, convert them, or merge on your PC, Mac
								or android browser with no additional software installation
								required for this process
							</p>
						</div>

						<!-- 24/7 Support -->
						<div class="why-reason">
							<div class="why-head">
								<img src="" alt="" />
								<h3 class="why-title">24/7 Support</h3>
							</div>
							<p class="why-desc">
								Our support team is always available 24/7 to assist, so you can
								reach out to us, to inquire or drop a feedback on our features
								and service
							</p>
						</div>
					</div>
				</div>
			</section>

			<!-- Used by -->
			<section class="used-section">
				<div class="container used-container">
					<h1 class="section-title">Organizations that use ChunkFile</h1>
					<div class="users">
						<img class="user" src="{% static 'images/zuri.png' %}" alt="" />
						<img class="user" src="{% static 'images/i4g.png' %}" alt="" />
						<img class="user" src="{% static 'images/jumia.png' %}" alt="" />
						<img class="user" src="{% static 'images/kpmg.png' %}" alt="" />
						<img class="user" src="{% static 'images/whogohost.png' %}" alt="" />
					</div>
				</div>
			</section>

			<!-- How it Works  -->
			<section>
				<div class="container how-container">
					<h1 class="section-title">How it Works</h1>
					<div class="hows">
						<!-- select a tool  -->
						<div class="how">
							<p class="how-num">1</p>
							<div class="how-top">
								<img src="{% static 'images/select.svg' %}" alt="" />
							</div>
							<div class="how-desc">
								<h3>Select a Tool</h3>
								<p>
									Get started by either choosing to split, convert, or merge
									your file
								</p>
							</div>
						</div>

						<!-- Upload a File  -->
						<div class="how">
							<p class="how-num">2</p>
							<div class="how-top">
								<img src="{% static 'images/upload.svg' %}" alt="" />
							</div>
							<div class="how-desc">
								<h3>Upload a File</h3>
								<p>Upload a file from your PC, or you simply paste a link</p>
							</div>
						</div>

						<!-- Set Parameters  -->
						<div class="how">
							<p class="how-num">3</p>
							<div class="how-top">
								<img src="{% static 'images/parameter.svg' %}" alt="" />
							</div>
							<div class="how-desc">
								<h3>Set Parameters</h3>
								<p>
									Choose the desired size you wish to split to, what files to
									convert or the files to merge
								</p>
							</div>
						</div>

						<!-- Download  -->
						<div class="how">
							<p class="how-num">4</p>
							<div class="how-top">
								<img src="{% static 'images/download.svg' %}" alt="" />
							</div>
							<div class="how-desc">
								<h3>Download</h3>
								<p>
									Your files are ready to download, you can also save for later
									or to cloud
								</p>
							</div>
						</div>
					</div>
				</div>
			</section>

			<!-- faq  -->
			<section>
				<div class="container faq-container">
					<h1 class="section-title">Frequently Asked Question</h1>
					<div class="faq">
						<div class="faq-group">
							<h3 class="faq-title">How to use ChunkFiles for free?</h3>
							<p class="faq-desc">
								ChunkFile provides an online platform to Split, Convert, Merge
								100% free, once you sign up by simply choosing a tool, uploading
								your preferred file format and either save to cloud or download
								immediately
							</p>
						</div>

						<div class="faq-group">
							<h3 class="faq-title">Can i use ChunkFile my PC?</h3>
							<p class="faq-desc">
								ChunkFile supports multiple platforms, from your PC, Mac,
								Iphone, and Android by simply opening on any of your browser
								without worrying about any software installation.
							</p>
						</div>

						<div class="faq-group">
							<h3 class="faq-title">How to Split Files?</h3>
							<p class="faq-desc">
								ChunkFile supports multiple platforms, from your PC, Mac,
								Iphone, and Android by simply opening on any of your browser
								without worrying about any software installation.
							</p>
						</div>

						<div class="faq-group">
							<h3 class="faq-title">How to Convert Files?</h3>
							<p class="faq-desc">
								ChunkFile supports multiple platforms, from your PC, Mac,
								Iphone, and Android by simply opening on any of your browser
								without worrying about any software installation.
							</p>
						</div>

						<div class="faq-group">
							<h3 class="faq-title">How to Merge Files?</h3>
							<p class="faq-desc">
								ChunkFile supports multiple platforms, from your PC, Mac,
								Iphone, and Android by simply opening on any of your browser
								without worrying about any software installation.
							</p>
						</div>
					</div>
				</div>
			</section>

			<!-- get in touch -->
			<section>
				<div class="container contact-container">
					<div class="contact-left">
						<img src="{% static 'images/247.svg' %}" alt="" />
					</div>

					<div class="contact-right">
						<h2>Get in touch</h2>
						<p>
							Have an inquiry or feedback for us? Kindly fill the form to reach
							out to us.
						</p>

						<form class="contact-form">
							<div class="form-group">
								<label for="fullname">Full Name</label>
								<input type="text" placeholder="Enter your full name here" />
							</div>

							<div class="form-group">
								<label for="emaileryidfv">Email Address</label>
								<input
									type="email"
									placeholder="Enter your Email Address here"
								/>
							</div>

							<div class="form-group">
								<label for="message"></label>
								<textarea
									name=""
									id=""
									cols="30"
									rows="10"
									placeholder="Enter your message here"
								></textarea>
							</div>

							<button>Get in touch</button>
						</form>
					</div>
				</div>
			</section>
		</main>

		{% include 'footer.html' %}

	</body>
</html>

Backend/templates/navbar.html
{% load static %}
    <nav>
      <div class="nav-container">
        <div class="nav-logo">
          <a href="{% url 'main:index' %}"
            ><img src="{% static 'images/header-logo1.svg' %}" alt=""
          /></a>
          <div id="burger">
            <h2><i class="fa-solid fa-bars"></i></h2>
          </div>
        </div>
        <div id="links" class="dropdown">
          <ul class="navbar-nav">
            <li>
              <a href="{% url 'split_file:split_home' %}" class="links active"
                >Home</a
              >
            </li>
            <li><a href="{% url 'main:about' %}" class="links">About Us</a></li>
            <li><a href="{% url 'main:faq' %}" class="links">FAQ</a></li>
            <li>
              <a href="{% url 'main:contact' %}" class="links">Contact Us</a>
            </li>
          </ul>
        </div>

        <div id="flex" class="dropdown">
          <form>
            <input type="search" name="" id="" placeholder="Search" />
          </form>
          <ul>
            <li>
              <a href="#"
                ><i
                  class="fa-regular fa-bell"
                  style="color: rgb(59, 91, 177)"
                ></i
              ></a>
            </li>
            <!-- profile -->
            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
            <li>
              <a href="#" class="profile">
                <!--profile-img added here -->
                <span class="bubble"><!--message no here -->8</span>
              </a>
            </li>
            <!-- <i class="fa-solid fa-user"></i> -->
          </ul>
        </div>
      </div>
    </nav>

Backend/templates/split_file/splitcsv.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="{% static 'css/splitcsv.css' %}" />
		<title>Split CSV</title>
	</head>
	<body>
		<header></header>
		<main>
			<section class="split-section">
				<div class="container">
					<h2 class="split-title">Split CSV Files</h2>
					<div class="main-split-container">
						<form action="" method="post" enctype="multipart/form-data">
							{% csrf_token %}
							<div class="upload">
							<div class="choose-file">
								<input type="file" name='csv_file' accept="csv"/>
							</div>
							<div class="drag-file">
								<input type="text" placeholder="or Drag file here" />
								<img src="../../assets/drive.svg" alt="" />
							</div>
						</div>
						</form>
						 

						<div class="progress">
							<div class="progress-container">
								<div class="progress-bar">
									<span data-width="100%"></span>
								</div>
							</div>
						</div>


						<div class="split">
							<div class="split-contain">
								<h2>Split CSV FIle</h2>
								<p>Split into as many files as you want</p>
								<div class="split-setting">
									<div class="left">
										<label for="size">Size of split files</label>
										<input type="text" placeholder="5mb" />
									</div>

									<div>
										<label for="line">Number of lines per file</label>
										<input type="text" placeholder="100" />
									</div>
								</div>

								<button>Split CSV</button>
							</div>
						</div>

						<div class="splitting">
							<h2>Splitting</h2>
							<img src="../../assets/loading.svg" alt="" />
							<button>Cancel</button>
						</div>

						<div class="splitted">
							<h2>Your file has been splited successfully</h2>
							<p>bodyguard_csv.zip</p>
							<div class="btn-group">
								<button class="download">Download</button>
								<button class="save">Save for later</button>
							</div>
						</div>
					</div>
				</div>
			</section>
		</main>

		<footer></footer>

		<script src="{% static 'js/progress.js' %}"></script>
	</body>
</html>